spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/film_buff
spring.datasource.username=root
spring.datasource.password=ritvik@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YzZhMTAyODExZWRkNGE2YWJmYmZiZDFmMjc1ODI2ZiIsIm5iZiI6MTc1NjQ3ODM0My40OTIsInN1YiI6IjY4YjFiYjg3YmM5MWZkODU0NDE1NzFkZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.aEDGu-TNwM6zP-4N_cIlYnuTGCakpghXvRFWmmMRwko
tmdb.base-url=https://api.themoviedb.org/3

server.port=8080